Create intregration specs
Mike47ip/Blog-app pull request #8
Opened 2023-11-14 15:18 UTC by Mike47ip

### Project requirements

#### n+1
- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
    - Do not use the bullet gem in this exercise - instead analyze the logs as showed in this [article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh)
    - **In your PR description include the screenshots of your app's logs before and after the fix**
    - This is the corresponding wireframe view: ![blog all user posts](../images/blog_user_all_posts.png)

#### Integration specs
- Use Capybara to write integration tests for each view in your project.
- Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

**Be sure to include integration specs for any other features you may have implemented!**

2023-11-14 15:56 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-14 15:56 UTC, Omar-Muhamad commented on spec/features/user_show_spec.rb
> +    end
- [ ] This test-case is supposed to test `when I click a user's post, it redirects me to that post's show page`, not expecting the content of the page when visiting the post show page as you did. Please write a proper test for the case.

[Hint] You can do something like that:
```ruby
click_link 'post 1 title'
expect(page).to have_current_path("/users/#{@user2.id}/post/#{@post1.id}")
```

2023-11-14 15:56 UTC, Omar-Muhamad commented on spec/features/user_show_spec.rb
> +    end
- [ ] For this case you are not testing the content of the page when the `see all posts` button is clicked. You are testing the current path you got when the `See all posts` button is clicked. Please fix that

2023-11-14 15:56 UTC, Omar-Muhamad commented on spec/features/user_show_spec.rb
> +    #                      posts_counter: 0)
- [ ] It's considered a good practice to have a readable code that is clean of any commented (unused) code. Please remove this commented code.

2023-11-14 15:56 UTC, Omar-Muhamad commented on spec/features/post_index_spec.rb
> +      expect(page).to have_content 'post 1 title by Lawrence'
- [ ] Same here, You are testing the current path of the page when the post is clicked, not the content of the page. So please fix that.

2023-11-16 09:51 UTC, Mike47ip commented on spec/features/user_show_spec.rb
> +    end
Hello @Omar-Muhamad  I have spent the last 3 days trying to implement you method but it is not working. Can we meet on zoom please?. Time is runniong out

2023-11-18 15:54 UTC, TadesseDev approved these changes
### Hi @Mike47ip 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![AmazingCreepyFrogmouth-max-1mb](https://user-images.githubusercontent.com/69077061/255314805-13569584-0c0e-4b38-a0bd-94d901ba8a1e.gif)




## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅


## Optional suggestions

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-18 15:54 UTC, TadesseDev commented on spec/features/user_show_spec.rb
>      end
- [Optional] Dear @Mike47ip, Good job making the suggested changes, But I noticed some other of your tests are still falling. When we write tests we need to make sure all the tests are passing. Please work on these tests and make sure all are passing. 

### The issue 
<img width="1136" alt="Screenshot 2023-11-18 at 6 48 45 in the evening" src="https://github.com/Mike47ip/Blog-app/assets/69077061/bb679be1-02ac-406f-be56-89a0a596e18d">

2023-11-19 17:24 UTC, merged